import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"], weight: ["400", "500", "600", "700"],
});

  const playfair_Display = Playfair_Display({
  subsets: ["latin"], weight: ["400", "800"],
});  

export const metadata = {
  title: "Shayonis World",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${inter.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
